#!/usr/bin/perl
use warnings;
use strict;

use open (":encoding(UTF-8)", ":std" );

use ArabicRegex;
use Unicode::UCD 'namedseq';

use PV;

# tatweel=ـ
my $tat = namedseq('ARABIC TATWEEL');

while(<>) {
  chomp;
  my $str = $_;
  my $re = arabic_to_regex($str);
  print sv($re),"\n";
  print ("$str --> $re\n");
  print (join("$tat",split('', $re)),"\n");
  #pv '$re';
  print ((($str =~ /$re/) ? "matches" : "no match"),"\n");
  # make the diacritics more readable
}
