#!/usr/bin/perl
use warnings;
use strict;

# Tool to check that alphabet-order, from Wikipedia, agrees with
# Perl's (unicode's?) sorting order

use open (":encoding(UTF-8)", ":std" );

open IN, "<", "alphabet-order" or die;

my @l;
while(<IN>) {
  chomp;
  my @e = split /\s+/, $_;
  push @l,@e;
}
#print join("\n",reverse @l),"\n";
@l = sort @l;
print join("\n",@l),"\n";
