#!/usr/bin/perl
use warnings;
use strict;

use Encode::Arabic;                 # imports just like 'use Encode' even with options would

while (<>) {
  $_ = decode 'utf8', $_;
  for my $e (qw(utf8 arabtex buckwalter arabtex-verbatim arabtex-zdmg parkinson habash)) {
      print "$e: ", (encode $e, $_);
  }
  print "\n";
}
