#!/bin/sh

# Custom script to compile a multimarkdown document into html

# FHE 05 Sep 2018 adapted from study/arabic/

#local OPTIND
while getopts "D" x; do
    case $x in
        D) insert_date=1;;
    esac
done
shift $(($OPTIND - 1))
#echo insert_date=$insert_date

if [[ $# -ne 1 ]]; then
    >&2 echo Need to specify filename;
    exit 1
fi
FN=$1
if [[ -z "$FN" ]]; then >&2 echo Empty filename; exit 1; fi

if [[ $(basename $FN) == INDEX.md ]]; then
    OUT=$(dirname $FN)/index.html
else
    OUT=${FN%.md}.html
fi

>&2 echo Writing to $OUT

multimarkdown $FN -o - | \
    # get rid of <p> around main <div>
    perl -pe '/<div id="page-wrap">/ && s/<\/?p>//g' | \
    grep -v 'my-source-command' | \
    # remove closing tags
    head -n -3 \
    > $OUT

if [[ $insert_date -ne 0 ]]; then
    >&2 echo inserting date
    cat >> $OUT <<EOF
<p><em>Last updated: $(date +'%-d %B %Y')</em></p>
</div>
</body>
</html>
EOF
else
    cat >> $OUT <<EOF
</div>
</body>
</html>
EOF
fi
