#!/usr/bin/perl
use warnings;
use strict;
BEGIN { push @INC, ".", "utils", "perl"; }

use ArabicTeX;
use ReadTable;

use U;

use Getopt::Long;
Getopt::Long::Configure ("bundling", "no_ignore_case");

sub usage {
  warn "Usage: table-to-cards [-v] -f FOOT_FMT -o OUT_BASE  TABLE_FILES\n";
  exit shift;
}

my (@tab_files,
    $verbose,
    $help,
    $bad_args,
    $output_base,
    $keep_aux
    );

GetOptions('-v' => \$verbose,
           '-f|foot=s' => \$foot_fmt,
           '-o' => \$output_base,
           '-h|help' => \$help,
           'keep-aux' => \$keep_aux
    ) or usage 1;

usage 0 if $help;

$PV::debug = $ReadTable::verbose = $verbose;

@tab_files = @ARGV or do {
  die "Need to specify an input table\n";
};

my $out_tex;
my $outputting = 1;

if($outputting) {
  if(!defined $output_base) {
    if(@tab_files>1) {
      die "Need to specify output base when using multiple inputs";
    } else {
      ($output_base = $tab_files[0]) =~ s/\..*?$//;
    }
    warn "Writing to $output_base.*\n";
    pv '$output_base';

    $out_tex = "$output_base.gen.tex";
    warn "Writing to $out_tex\n";
    open OUT, ">", $out_tex or die "Couldn't open $out_tex for writing\n";

    print OUT <<\EOF;
% my-latex-command: xelatex
\input{tex/arab_fc_common.tex}
\begin{document}
\cardfrontstyle{headings}
EOF
  }
}

sub card {
  my ($arabic,$english,$group) = @_;
  my ($foot) = format_group $group;
  my ($artransl);
  if($arabic =~ /^(.*?)\s*\|\|\s*(.*)$/) {
    ($arabic, $artransl) = ($1, $2);
    $artransl = arabic_fixup $artransl;
  }
  $arabic = arabic_fixup $arabic;
  $english = arabic_fixup $english;
  pv '$foot';
  pv '$group';
  my $arabic_side;

  # if a transliteration is provided, use a tabularx to get left/right
  # formatting
  if(!defined $artransl) {
    $arabic_side = "\\LARGE $arabic";
  } else {
    $arabic_side =
"\\LARGE \\begin{tabularx}{\\textwidth}{>{\\raggedright}X>{\\raggedleft}X}
$artransl & $arabic \\\\
\\end{tabularx}";
  }
  
  print OUT <<EOF;
\\cardfrontfoot{$foot}
\\begin{flashcard}{\\LARGE $english}
$arabic_side
\\end{flashcard}
EOF
}

read_table(\&card, \@tab_files);

if($outputting) {
  print OUT "\\end{document}\n";
  close OUT;

  sh ("xelatex $out_tex < /dev/null");
  rename ("$output_base.gen.pdf", "$output_base.pdf");
  if(!$keep_aux) {
    unlink "$output_base.gen.log";
    unlink "$output_base.gen.aux";
    unlink "$output_base.gen.tex";
  }
}
