#!/usr/bin/perl
use warnings;
use strict;

BEGIN { unshift @INC, "perl"; }
use ArabicTeX;
use open ( ":encoding(UTF-8)", ":std" );

while(<>) {
  #  /[\p{Script=Arabic}]/ && print "Found Arabic\n";
  chomp;
  print arabic_fixup($_),"\n";
}
